# Generated by Django 3.1.1 on 2021-06-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210616_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_login',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='tbl_login',
            name='pictures',
        ),
    ]
