# Generated by Django 3.1.1 on 2021-07-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210621_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_login',
            name='password',
        ),
    ]
