# Generated by Django 3.1.1 on 2021-07-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
